trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - powershell: 'Get-ChildItem Env:'
  - script: sudo apt install libfontconfig1-dev -y
    condition: eq('$(Agent.JobName)', 'linux')
  - script: dotnet run -c Release -p SkiaSharpBenchmarks
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: '$(Agent.JobName)_results'
      targetPath: 'SkiaSharpBenchmarks/BenchmarkDotNet.Artifacts/'
