trigger:
  - master

jobs:
  - job: windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: dotnet run -c Release -p SkiaSharpBenchmarks

  - job: ubuntu16
    pool:
      vmImage: ubuntu-16.04
    container: ubuntu:16.04
    steps:
      - bash: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev dotnet-sdk-2.2
      - script: dotnet run -c Release -p SkiaSharpBenchmarks

  - job: macos
    pool:
      vmImage: macos-10.13
    steps:
      - script: dotnet run -c Release -p SkiaSharpBenchmarks
