
trigger:
  - master

jobs:
  - job: old_library
    pool:
      vmImage: macos-10.13
    steps:
      - script: dotnet run -c Release -p SkiaSharpBenchmarks
        env:
          LIBRARY_VERSION: 'old'
  - job: new_library
    pool:
      vmImage: macos-10.13
    steps:
      - script: dotnet run -c Release -p SkiaSharpBenchmarks
        env:
          LIBRARY_VERSION: 'new'
