
trigger:
  - master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
  - task: UseDotNet@2
    inputs:
      version: 3.0.x
  - script: msbuild /r /v:m /p:Configuration=Release
  - script: SkiaSharpBenchmarks\bin\Release\netcoreapp3.0\SkiaSharpBenchmarks.exe
