
trigger:
  - master

jobs:
  - job: windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: dotnet run -c Release -p SkiaSharpBenchmarks

  - job: ubuntu16
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: dotnet run -c Release -p SkiaSharpBenchmarks

  - job: macos
    pool:
      vmImage: macos-10.13
    steps:
      - script: brew install mono-libgdiplus
      - script: dotnet run -c Release -p SkiaSharpBenchmarks
