trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
  - script: dotnet run -c Release -p SkiaSharpBenchmarks
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: results
      targetPath: '*/BenchmarkDotNet.Artifacts/'

