
trigger:
  - master

strategy:
  matrix:
    macos:
      imageName: Hosted macOS
    windows:
      imageName: Hosted Windows 2019 with VS2019

pool:
  name: $(imageName)

steps:
  - script: dotnet run -c Release -p SkiaSharpBenchmarks
